# Generated by Django 5.0 on 2026-02-03 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ex: BTC, ETH', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Ex: Bitcoin, Ethereum', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crypto_configuration',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='DataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('cache_value', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_cache',
                'indexes': [models.Index(fields=['cache_key'], name='data_cache_cache_k_656e30_idx'), models.Index(fields=['expires_at'], name='data_cache_expires_5307aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisualizationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crypto_symbol', models.CharField(max_length=50)),
                ('time_range', models.CharField(help_text='Ex: 24h, 7d, 30d', max_length=20)),
                ('chart_type', models.CharField(help_text='Ex: candlestick, line', max_length=50)),
                ('indicators', models.JSONField(default=list, help_text='Liste des indicateurs actifs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visualization_parameters',
                'ordering': ['-created_at'],
            },
        ),
    ]
