# Generated by Django 5.0 on 2026-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizationparameter',
            name='time_range',
            field=models.CharField(help_text='Ex: live, 1min, 5min, 15min, 30min, 1h, 24h, 7d, 30d', max_length=20),
        ),
    ]
